// Package export generates standalone Go code snippets for animations.
package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const template = `package main

import (
	"fmt"
	"time"
)

// Animation: %s
// Generated by ascii-animations showcase

func main() {
	frames := []string{
%s	}
	interval := %d * time.Millisecond

	fmt.Print("\033[?25l") // hide cursor
	defer fmt.Print("\033[?25h\n") // show cursor

	for i := 0; ; i++ {
		frame := frames[i%%len(frames)]
		fmt.Print("\033[H") // move cursor to top-left
		fmt.Print(frame)
		time.Sleep(interval)
	}
}
`

// Generate creates a standalone Go file for the given frames and writes it to dir.
func Generate(name string, frames []string, interval time.Duration, dir string) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create export dir: %w", err)
	}

	slug := strings.ReplaceAll(strings.ToLower(name), " ", "_")
	slug = strings.ReplaceAll(slug, ":", "_")
	filename := filepath.Join(dir, slug+".go")

	var framesBuf strings.Builder
	for _, f := range frames {
		escaped := strings.ReplaceAll(f, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		escaped = strings.ReplaceAll(escaped, "\033", "\\033")
		escaped = strings.ReplaceAll(escaped, "\n", "\\n")
		framesBuf.WriteString(fmt.Sprintf("\t\t\"%s\",\n", escaped))
	}

	content := fmt.Sprintf(template, name, framesBuf.String(), interval.Milliseconds())

	if err := os.WriteFile(filename, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write export: %w", err)
	}
	return filename, nil
}

// Snippet returns the Go source code as a string without writing to disk.
func Snippet(name string, frames []string, interval time.Duration) string {
	var framesBuf strings.Builder
	for _, f := range frames {
		escaped := strings.ReplaceAll(f, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		escaped = strings.ReplaceAll(escaped, "\033", "\\033")
		escaped = strings.ReplaceAll(escaped, "\n", "\\n")
		framesBuf.WriteString(fmt.Sprintf("\t\t\"%s\",\n", escaped))
	}
	return fmt.Sprintf(template, name, framesBuf.String(), interval.Milliseconds())
}
